import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [jackson-datatype-jsr310 website](https://github.com/FasterXML/jackson-modules-java8) */
    const val jackson_datatype_jsr310: String =
            "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:" + Versions.jackson_datatype_jsr310

    /**
     * [disruptor website](http://lmax-exchange.github.com/disruptor) */
    const val disruptor: String = "com.lmax:disruptor:" + Versions.disruptor

    /**
     * [DbSetup-kotlin website](http://dbsetup.ninja-squad.com/) */
    const val dbsetup_kotlin: String = "com.ninja-squad:DbSetup-kotlin:" + Versions.dbsetup_kotlin

    /**
     * [HikariCP website](https://github.com/brettwooldridge/HikariCP) */
    const val hikaricp: String = "com.zaxxer:HikariCP:" + Versions.hikaricp

    const val ktor_client_apache: String = "io.ktor:ktor-client-apache:" + Versions.io_ktor

    const val ktor_client_jackson: String = "io.ktor:ktor-client-jackson:" + Versions.io_ktor

    const val ktor_jackson: String = "io.ktor:ktor-jackson:" + Versions.io_ktor

    const val ktor_server_core: String = "io.ktor:ktor-server-core:" + Versions.io_ktor

    const val ktor_server_netty: String = "io.ktor:ktor-server-netty:" + Versions.io_ktor

    /**
     * [mockk website](http://mockk.io) */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [owner-java8 website](http://owner.aeonbits.org) */
    const val owner_java8: String = "org.aeonbits.owner:owner-java8:" + Versions.owner_java8

    /**
     * [log4j-api website](https://logging.apache.org/log4j/2.x/) */
    const val log4j_api: String =
            "org.apache.logging.log4j:log4j-api:" + Versions.org_apache_logging_log4j

    /**
     * [log4j-core website](https://logging.apache.org/log4j/2.x/) */
    const val log4j_core: String =
            "org.apache.logging.log4j:log4j-core:" + Versions.org_apache_logging_log4j

    /**
     * [log4j-jcl website](https://logging.apache.org/log4j/2.x/) */
    const val log4j_jcl: String =
            "org.apache.logging.log4j:log4j-jcl:" + Versions.org_apache_logging_log4j

    /**
     * [log4j-jul website](https://logging.apache.org/log4j/2.x/) */
    const val log4j_jul: String =
            "org.apache.logging.log4j:log4j-jul:" + Versions.org_apache_logging_log4j

    /**
     * [log4j-slf4j-impl website](https://logging.apache.org/log4j/2.x/) */
    const val log4j_slf4j_impl: String =
            "org.apache.logging.log4j:log4j-slf4j-impl:" + Versions.org_apache_logging_log4j

    /**
     * [assertj-core website](http://assertj.org) */
    const val assertj_core: String = "org.assertj:assertj-core:" + Versions.assertj_core

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" + Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    const val org_jetbrains_kotlin_kapt_gradle_plugin: String =
            "org.jetbrains.kotlin.kapt:org.jetbrains.kotlin.kapt.gradle.plugin:" + Versions.org_jetbrains_kotlin_kapt_gradle_plugin

    /**
     * [kotlin-annotation-processing-gradle website](https://kotlinlang.org/) */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.kotlin_annotation_processing_gradle

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.kotlin_scripting_compiler_embeddable

    /**
     * [kotlin-stdlib-jdk8 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk8: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" + Versions.kotlin_stdlib_jdk8

    /**
     * [kotlinx-coroutines-core website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:" + Versions.kotlinx_coroutines_core

    /**
     * [junit-jupiter-api website](http://junit.org/junit5/) */
    const val junit_jupiter_api: String =
            "org.junit.jupiter:junit-jupiter-api:" + Versions.org_junit_jupiter

    /**
     * [junit-jupiter-engine website](http://junit.org/junit5/) */
    const val junit_jupiter_engine: String =
            "org.junit.jupiter:junit-jupiter-engine:" + Versions.org_junit_jupiter

    const val org_liquibase_gradle_gradle_plugin: String =
            "org.liquibase.gradle:org.liquibase.gradle.gradle.plugin:" + Versions.org_liquibase_gradle_gradle_plugin

    /**
     * [liquibase-core website](http://www.liquibase.org) */
    const val liquibase_core: String = "org.liquibase:liquibase-core:" + Versions.liquibase_core

    /**
     * [mybatis-typehandlers-jsr310 website](https://github.com/mybatis/typehandlers-jsr310) */
    const val mybatis_typehandlers_jsr310: String =
            "org.mybatis:mybatis-typehandlers-jsr310:" + Versions.mybatis_typehandlers_jsr310

    /**
     * [mybatis website](http://www.mybatis.org/mybatis-3) */
    const val mybatis: String = "org.mybatis:mybatis:" + Versions.mybatis

    /**
     * [postgresql website](https://github.com/pgjdbc/pgjdbc) */
    const val postgresql: String = "org.postgresql:postgresql:" + Versions.postgresql
}
